version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

jobs:
  build:
    executor: continuation/default
    steps:
      - checkout
      - run:
          command: |
            # check the commit message of the latest commit
            if git show --format=%B --quiet | grep -i "\[noci\]"; then
              echo '[noci] is found in the latest commit message. Halting the job.'
              circleci-agent step halt
              exit
            fi
      - continuation/continue:
          configuration_path: .circleci/main.yml
