version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

jobs:
  build:
    executor: continuation/default
    steps:
      - checkout
      - run:
          command: |
            # check the commit message of the latest commit
            if [ $(git show --format=%B --quiet | grep -i "[noci]") ]; then
              cat .circleci/noop.yml > .circleci/pipeline.yml
            else
              cat .circleci/main.yml > .circleci/pipeline.yml
            fi
      - continuation/continue:
          configuration_path: .circleci/pipeline.yml
