version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

jobs:
  build:
    executor: continuation/default
    steps:
      - checkout
      - run:
          command: |
            echo hello
#       - continuation/continue:
#           configuration_path: .circleci/pipeline.yml
